import { Place } from './types';

export const PLACES: Place[] = [
  {
    id: '1',
    name: 'Parque da Cidade',
    category: 'nature',
    description: 'O pulmão da nossa região. Perfeito para um piquenique ou caminhada matinal. Possui trilhas bem iluminadas.',
    imageUrl: 'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?q=80&w=2070&auto=format&fit=crop',
    address: 'Av. das Nações, Centro',
    priceLevel: 0,
    priceExample: 'Entrada Gratuita',
    verifiedHours: '06:00 - 20:00 (Verificado hoje)',
    securityRating: 5,
    occupancy: 'busy',
    distance: '0.8 km',
  },
  {
    id: '2',
    name: 'Café do Beco',
    category: 'food',
    description: 'Cafeteria artesanal escondida em um dos becos mais charmosos. Famoso pelo pão de queijo recheado.',
    imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?q=80&w=2078&auto=format&fit=crop',
    address: 'Rua das Flores, 142',
    priceLevel: 1,
    priceExample: 'Cafés a partir de R$ 8,00',
    verifiedHours: '08:00 - 18:00 (Verificado ontem)',
    securityRating: 4,
    occupancy: 'moderate',
    distance: '1.2 km',
  },
  {
    id: '3',
    name: 'Museu de Arte Local',
    category: 'culture',
    description: 'Exposição rotativa de artistas da comunidade. Gratuito às quartas-feiras.',
    imageUrl: 'https://images.unsplash.com/photo-1518998053901-5348d3961a04?q=80&w=1974&auto=format&fit=crop',
    address: 'Praça da Matriz, s/n',
    priceLevel: 1,
    priceExample: 'Entrada: R$ 15,00 (Inteira)',
    verifiedHours: '10:00 - 17:00 (Verificado há 2 dias)',
    securityRating: 5,
    occupancy: 'calm',
    distance: '2.5 km',
  },
  {
    id: '4',
    name: 'Mirante do Sol',
    category: 'nature',
    description: 'O melhor pôr do sol da cidade. Acesso por trilha leve de 10 minutos.',
    imageUrl: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?q=80&w=2070&auto=format&fit=crop',
    address: 'Estrada do Morro, Km 4',
    priceLevel: 0,
    priceExample: 'Acesso Livre',
    verifiedHours: 'Aberto 24h (Pôr do sol recomendado)',
    securityRating: 3,
    occupancy: 'moderate',
    distance: '4.1 km',
  },
  {
    id: '5',
    name: 'Feira Gastronômica Noturna',
    category: 'food',
    description: 'Toda sexta à noite. Música ao vivo e comidas típicas de diversos moradores.',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=2074&auto=format&fit=crop',
    address: 'Praça Central',
    priceLevel: 1,
    priceExample: 'Pratos de R$ 12,00 a R$ 45,00',
    verifiedHours: '18:00 - 23:00 (Toda Sexta)',
    securityRating: 4,
    occupancy: 'busy',
    distance: '1.5 km',
  },
  {
    id: '6',
    name: 'Biblioteca Comunitária',
    category: 'culture',
    description: 'Espaço de coworking gratuito e acervo compartilhado. Silêncio e paz garantidos.',
    imageUrl: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?q=80&w=2190&auto=format&fit=crop',
    address: 'Rua do Saber, 45',
    priceLevel: 0,
    priceExample: 'Uso Gratuito',
    verifiedHours: '09:00 - 20:00 (Verificado hoje)',
    securityRating: 5,
    occupancy: 'calm',
    distance: '0.5 km',
  }
];
